name: SwiftFormat Check

on:
  push:
  pull_request:

jobs:
  swiftformat:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat
        run: swiftformat . --lint


