name: SwiftFormat PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  swiftformat:
    name: Run SwiftFormat
    runs-on: macos-latest  # Using macOS because SwiftFormat requires it

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat (without committing)
        run: swiftformat .

      - name: Post Formatting Suggestions to PR
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: SwiftFormat
          fail_on_error: true
          filter_mode: file
          level: warning
