name: SwiftFormat Auto-Fix

on:
  pull_request:
    branches:
      - main

jobs:
  swiftformat:
    name: Run SwiftFormat
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Swift
        run: swift --version  # Ensure Swift is installed

      - name: Resolve Swift Packages
        run: swift package resolve  # Ensures SwiftFormat is fetched correctly

      - name: Run SwiftFormat (Auto-Fix)
        run: swift run swiftformat .
