name: SwiftFormat Auto-Fix

on:
  pull_request:
    branches:
      - main

jobs:
  swiftformat:
    name: Run SwiftFormat
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Swift
        run: swift --version  # Ensure Swift is installed

      - name: Resolve Swift Packages
        run: swift package resolve  # Ensures SwiftFormat is fetched correctly

      - name: Run SwiftFormat (Using SPM)
        run: swift run swiftformat .

      - name: Commit and Push Fixes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Apply SwiftFormat fixes"
          git push
        continue-on-error: true
